### ISSUE TITLE
Timeline scroll-to off

### ISSUE THREAD

**Issue by simplemama** [hyunsupul/aesop-core#92]
Timeline scroll to is off. When you click a timeline stop in the nav, you are unable to see that timeline stop's title.

Temp CSS fix:

``` css
.scroll-nav__section {
  padding-top: 5%;
  margin-top: -5%;
}
```
